name: amd64_windows_vs2019

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  amd64_windows_vs2019:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - run: msbuild -version
    - run: cl
    - run: mingw32-make -f Makefile.win
    - run: file hello.exe
    - run: ./hello.exe
