name: amd64_macos_clang

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  amd64_macos_clang:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - run: cc --version
    - run: make
    - run: file ./hello
    - run: ./hello
