name: amd64_windows_tcc

on: [push, pull_request]

jobs:

  amd64_windows_tcc:
    runs-on: windows-2019
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3

    - name: Install tcc
      run: |
        echo "5a3979bd5044b795547a4948a5625a12  tcc.zip" > checksum.md5
        dos2unix checksum.md5
        curl -L -o tcc.zip https://archive.org/download/tinyccompiler/tcc-0.9.27-win32-bin.zip
        md5sum -c checksum.md5 && unzip -q tcc.zip

    - run: tcc\x86_64-win32-tcc.exe -v
    - run: make CC="tcc\x86_64-win32-tcc.exe"
    - run: ren hello hello.exe
    - run: file hello.exe
    - run: ./hello.exe
