name: amd64_macos_gcc

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  amd64_macos_gcc:
    runs-on: macos-12
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - run: brew install gcc@9
    - run: gcc-9 --version
    - run: CC=gcc-9 make
    - run: file ./hello
    - run: ./hello
