name: amd64_linux_gcc

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  amd64_linux_gcc:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install -y make gcc
    - run: gcc --version
    - run: CC=gcc make
    - run: file ./hello
    - run: ./hello
