name: amd64_linux_clang

on: [push, pull_request]

jobs:

  amd64_linux_clang:
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y make clang
    - run: clang --version
    - run: CC=clang make
    - run: file ./hello
    - run: ./hello
