name: amd64_windows_mingw

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  amd64_windows_mingw:
    runs-on: windows-2019
    timeout-minutes: 5
    env:
      CC: gcc
    steps:
    - uses: actions/checkout@v4
    - run: choco install mingw --version 8.1.0
    - run: gcc --version
    - run: make
    - run: file hello.exe
    - run: ./hello.exe
