name: amd64_linux_tcc

on: [push, pull_request]

jobs:

  amd64_linux_tcc:
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y make tcc
    - run: tcc -v
    - run: CC=tcc make
    - run: file ./hello
    - run: ./hello
