name: amd64_linux_clang

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  amd64_linux_clang:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt install -y make clang
    - run: clang --version
    - run: CC=clang make
    - run: file ./hello
    - run: ./hello
