name: amd64_windows_gcc

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  amd64_windows_gcc:
    runs-on: windows-2019
    timeout-minutes: 5
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        install: gcc make
    - run: gcc -v
    - run: make CC=gcc
    - run: file ./hello.exe
    - run: ./hello
