name: armhf_linux_gcc

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  armhf_linux_gcc:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    env:
      CC: ./armel-linux-musleabihf-cross/bin/armel-linux-musleabihf-gcc
      LDFLAGS: -static
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get -y -qq update
    - run: sudo apt install -y qemu-user
    - name: Prepare cross-compiler
      run: |
        curl -O https://musl.cc/armel-linux-musleabihf-cross.tgz
        tar xzf armel-linux-musleabihf-cross.tgz
    - name: Verify tools version
      run: ./armel-linux-musleabihf-cross/bin/armel-linux-musleabihf-gcc --version
    - run: make
    - run: file ./hello
    - run: qemu-arm ./hello
