name: i686_linux_clang

on: [push, pull_request]

jobs:

  i686_linux_clang:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get -y -qq update
    - run: sudo apt install -y make clang gcc-multilib qemu-user
    - run: clang --version
    - run: make CC=clang CFLAGS=-m32 LDFLAGS='-m32 -static'
    - run: file ./hello
    - run: qemu-i386 ./hello
