name: i686_windows_gcc

on: [push, pull_request]

jobs:

  i686_windows_gcc:
    runs-on: windows-2019
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2

    - run: C:\msys64\usr\bin\pacman --version
    - run: C:\msys64\usr\bin\pacman -Sy
    - run: C:\msys64\usr\bin\pacman --noconfirm -S pacman-mirrors
    - run: C:\msys64\usr\bin\pacman --noconfirm -S mingw-w64-cross-gcc

    - run: C:\msys64\opt\bin\i686-w64-mingw32-gcc -v
    - run: make CC=C:\msys64\opt\bin\i686-w64-mingw32-gcc
    - run: file ./hello.exe
    - run: ./hello
