name: i686_windows_clang

on: [push, pull_request]

jobs:

  i686_windows_clang:
    runs-on: windows-2019
    timeout-minutes: 5
    env:
      CC: clang
    steps:
    - uses: actions/checkout@v3

    - run: C:\msys64\usr\bin\pacman --version
    - run: C:\msys64\usr\bin\pacman -Sy
    - run: C:\msys64\usr\bin\pacman --noconfirm -S pacman-mirrors
    - run: C:\msys64\usr\bin\pacman --noconfirm -S mingw32/mingw-w64-i686-clang

    - run: C:\msys64\mingw32\bin\clang --version
    - run: make CC=C:\msys64\mingw32\bin\clang
    - run: file ./hello.exe
    - run: ./hello
