name: i686_windows_vs2019

on: [push, pull_request]

jobs:

  i686_windows_vs2019:
    runs-on: windows-2019
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    - run: cl
    - run: mingw32-make -f Makefile.win
    - run: file hello.exe
    - run: ./hello.exe
