name: mips_linux_gcc

on: [push, pull_request]

jobs:

  mips_linux_gcc:
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    env:
      CC: ./mips-linux-musl-cross/bin/mips-linux-musl-gcc
      LDFLAGS: -static
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get -y -qq update
    - run: sudo apt install -y qemu-user
    - name: Prepare cross-compiler
      run: |
        curl -O https://musl.cc/mips-linux-musl-cross.tgz
        tar xzf mips-linux-musl-cross.tgz
    - name: Verify tools version
      run: ./mips-linux-musl-cross/bin/mips-linux-musl-gcc --version
    - run: make
    - run: file ./hello
    - run: qemu-mips ./hello
